# Generated by Django 5.0.8 on 2024-08-11 14:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_rating_course_avg_rating_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='topic',
            new_name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='courses/videos'),
        ),
    ]
