# Generated by Django 5.0.8 on 2024-08-11 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_rating_course_avg_rating_comment_rating'),
        ('myCourses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paidcourse',
            unique_together={('user', 'course')},
        ),
    ]
