# Generated by Django 5.0.8 on 2024-08-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('course', '0003_comment_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
        migrations.AddField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
