# Generated by Django 5.0.8 on 2024-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balence',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
